import { PrismaClient } from '@prisma/client';

export async function seedCategories(prisma: PrismaClient) {
  await prisma.category.createMany({
    data: [
      { code: '01', name: 'BLAZER' },
      { code: '02', name: 'CHALECO' },
      { code: '03', name: 'TORERO' },
      { code: '04', name: 'CAPRI' },
      { code: '05', name: 'BIKER' },
      { code: '06', name: 'ALADINO' },
      { code: '07', name: 'BOMBACHO' },
      { code: '08', name: 'PANTY' },
      { code: '09', name: 'CACHETERO' },
      { code: '10', name: 'JEANS' },
      { code: '11', name: 'BLUSA' },
      { code: '12', name: 'CAMISETA' },
      { code: '13', name: 'CAMISA' },
      { code: '14', name: 'SHORT' },
      { code: '15', name: 'BERMUDA' },
      { code: '16', name: 'LEGGINS' },
      { code: '17', name: 'SUDADERA' },
      { code: '18', name: 'PANTALONETA' },
      { code: '19', name: 'FALDA' },
      { code: '20', name: 'VESTIDO' },
      { code: '21', name: 'ENTERIZO' },
      { code: '22', name: 'BODY' },
      { code: '23', name: 'CONJUNTO CALLE / DEPORTIVO' },
      { code: '24', name: 'MEDIAS' },
      { code: '25', name: 'BRASILERA' },
      { code: '26', name: 'BOXER' },
      { code: '27', name: 'BRASIER' },
      { code: '28', name: 'CONJUNTO INTERIOR (LENCERIA)' },
      { code: '29', name: 'BABYDOLL' },
      { code: '30', name: 'PIJAMAS' },
      { code: '31', name: 'PANTALÓN' },
      { code: '32', name: 'BUSO/CHAQUETA' },
      { code: '33', name: 'HAMACA' },
      { code: '34', name: 'TOP' },
      { code: '35', name: 'CAMISILLA' },
      { code: '36', name: 'PANTALONCILLO' },
      { code: '37', name: 'MANGAS' },
      { code: '38', name: 'CICLISTA' },
      { code: '39', name: 'BRAGA/OVEROL' },
      { code: '40', name: 'MAMELUCO' },
      { code: '41', name: 'VESTIDO DE BAÑO' },
      { code: '42', name: 'PAÑUELOS' },
      {
        code: '43',
        name: 'ACCESORIOS LINEA HOGAR (CORTINAS, COJINES, ALMOHADAS)',
      },
      { code: '44', name: 'ARTÍCULOS BEBÉ' },
      { code: '45', name: 'LIMPIÓN' },
      { code: '46', name: 'TANGA' },
      { code: '47', name: 'HILO' },
      { code: '48', name: 'TAPETE' },
      { code: '49', name: 'RUANA' },
      { code: '50', name: 'TOALLAS' },
      { code: '51', name: 'JOGGER' },
      { code: '52', name: 'SÁBANA/ ACOLCHADOS/ COBIJA' },
      { code: '53', name: 'BICICLETERO' },
      { code: '54', name: 'TAPABOCAS' },
      { code: '55', name: 'ZAPATOS' },
      { code: '56', name: 'FALDASHORT' },
      { code: '57', name: 'SALIDA DE BAÑO' },
      { code: '58', name: 'JARDINERA' },
      { code: '59', name: 'GORRAS' },
    ],
    skipDuplicates: true,
  });
}
